#!/bin/bash

set -ex

export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
app=daemon

export APP_EXEC_DIR=$SNAP/app

SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})
. $SCRIPT_DIR/init-base

declare -a args="($(cat $SNAP_COMMON/args/$app))"
if [ -f ${SNAP_COMMON}/args/${app}-env ]; then
  set -a
  . "${SNAP_COMMON}/args/${app}-env"
  set +a
fi

exec "$SNAP/bin/node" "$SNAP/app/bundle.js" "${args[@]}"
