name: fudge-docker-registry
version: git
summary: fudge-docker-registry service
description: |
    $ sudo systemctl enable fudge-docker-registry.service
    $ sudo systemctl start fudge-docker-registry.service
confinement: devmode
base: core18

parts:
  wethr:
    plugin: nodejs
    source: ../

#apps:
#  wethr:
#    command: wethr
